scrolling {
  # Scrolling is now in stable.
  # So stop using the mouse pointer to scroll
  # follow_min_visible = 0.0
  follow_min_visible = 0.333

}

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}