################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitorv2 {
  output = eDP-1
  mode = 2560x1600@60
  #mode = 2560x1600@165
  #cm = dcip3
  vrr = 2
  scale = 1
}
