-- Set programs that you use
Terminal     = "kitty"
FileExplorer = "dolphin"
-- Menu         = "rofi -show drun"
Menu         = "noctalia msg panel-toggle launcher"
PowerMenu    = "pidof rofi || $HOME/.config/rofi/menus/power.sh"
-- PowerMenu    = "noctalia msg panel-toggle session"
Lock         = "hyprlock"
-- Clipboard    = "pidof nwg-clipman || nwg-clipman"
Clipboard    = "noctalia msg panel-toggle clipboard"
