#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Don't know if this does anything. Maybe I got lucky and had a well-calibrated display on arrival? Maybe it doesn't work.
# exec-once = dispwin /usr/share/color/icc/colord/BOE_CQ_______NE160QDM_NZ6.icm
exec-once = systemctl --user start hyprpolkitagent # polkit agent
exec-once = systemctl --user start hyprpaper.service
exec-once = systemctl --user start hypridle.service

exec-once = hyprpm reload # plugins, -n sends a notification each time
exec-once = hyprcursor # hyprland stuff
exec-once = waybar & swayosd-server & swaync # other UI stuff
exec-once = nm-applet & blueman-applet & opensnitch-ui # tray
# exec-once = systemctl --user start gpu-screen-recorder
exec-once = gsr-ui



# Clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data