# vim:ft=kitty

## name: Golem, based on GitHub Dark
## author: golem16

#: The basic colors

foreground #dadada
# Standard theme bg -5% brightness
background #20222c
selection_foreground #20222c
selection_background #6c82ef


#: Cursor colors

cursor #6c82ef


#: Tab bar colors

tab_bar_background #010409
active_tab_foreground #dadada
active_tab_background #20222c
inactive_tab_foreground #8b949e
inactive_tab_background #010409


#: The basic 16 colors

#: black
color0 #484f58
color8 #6e7681

#: red
color1 #ff7b72
color9 #ffa198

#: green
color2 #3fb950
color10 #56d364

#: yellow
color3 #d29922
color11 #e3b341

#: blue
color4 #6c82ef
color12 #79c0ff

#: magenta
color5 #bc8cff
color13 #d2a8ff

#: cyan
color6 #39c5cf
color14 #56d4dd

#: white
color7 #b1bac4
color15 #ffffff
