# Noctalia theme for snappy-switcher

[colors]
background = #1e1e2eaa
card_bg = #313244aa
card_selected =  #42435cff
text_color = #e4d0fbdd
subtext_color =  #e4d0fbcc
border_color =  #646883ff
bundle_bg = #c75107ff
badge_bg =  #fab387aa
badge_text_color = #11111baa
badge_bg_selected = #fab387cc
badge_text_color_selected = #11111bff