general {
  lock_cmd = pidof hyprlock || hyprlock --grace 3 # avoid starting multiple hyprlock instances.
  before_sleep_cmd = loginctl lock-session # lock before suspend.
  after_sleep_cmd = hyprctl dispatch dpms on # && notify-send "Awake from sleep." # to avoid having to press a key twice to turn on the display.
}

# Lock
listener {
  # in seconds
  timeout = 60
  on-timeout = loginctl lock-session
  # on-timeout = notify-send "You are idle!"
  # on-resume = notify-send "Welcome back!"
}

# Screen off
listener {
  # in seconds
  timeout = 90
  on-timeout = hyprctl dispatch dpms off # Display off
  on-resume = hyprctl dispatch dpms on # Display on
}

# Sleep
# This doesn't seem to work
listener {
    timeout = 900 # 15 minutes
    on-timeout = systemctl suspend
}