source=~/.config/hypr/theme.conf

font_family = CaskaydiaMono Nerd Font Mono
font_family_monospace = CaskaydiaMono Nerd Font Mono

# Make them larger on HiDPI screens
h1_size = 28
h1_size = 24
h1_size = 22
# font_size = 20
font_size = 16

background = $htBackground
base = $htBackgroundSecondary
alternate_base = $htBackgroundTertiary

text = $htText