# Based on hsl(231 16% 16%)
$outlineDefault = rgb(515670)
$outlineFocused = rgb(949fdb)

$htBackground = rgb(2b2d3b)
$htBackgroundSecondary = rgb(404359)
$htBackgroundTertiary = rgb(555977)

$htText = rgb(dadada)